services:
    # El motor de PHP
    php:
        build: .
        volumes:
            - .:/var/www/html

    # El servidor web (Nginx)
    nginx:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    # Tu base de datos (la que ya tenías)
    database:
        image: postgres:16-alpine
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: app
            POSTGRES_DB: app
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data # <--- AÑADE ESTO

    # Tu servidor de correo (el que ya tenías)
    mailer:
        image: axllent/mailpit
        ports:
            - "8025:8025"
            - "1025:1025"

    mercure:
        image: dunglas/mercure
        restart: always
        environment:
            # La misma clave de 32 caracteres que en el .env de Symfony
            SERVER_NAME: ":3000"
            MERCURE_PUBLISHER_JWT_KEY: "brainhub_secret_32_characters_long_key"
            MERCURE_SUBSCRIBER_JWT_KEY: "brainhub_secret_32_characters_long_key"
            # --- ESTAS LÍNEAS SON LAS QUE TE FALTAN ---
            MERCURE_EXTRA_DIRECTIVES: |
                anonymous
                subscriptions
                cors_origins *
                ui
        ports:
            - "3000:3000"



volumes:
    postgres_data:
