<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260409174044 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE archivo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre_original VARCHAR(255) NOT NULL, nombre_servidor VARCHAR(255) NOT NULL, tipo VARCHAR(50) NOT NULL, sala_id INT NOT NULL, subido_por_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3529B482C51CDF3F ON archivo (sala_id)');
        $this->addSql('CREATE INDEX IDX_3529B482446C2E6 ON archivo (subido_por_id)');
        $this->addSql('ALTER TABLE archivo ADD CONSTRAINT FK_3529B482C51CDF3F FOREIGN KEY (sala_id) REFERENCES sala (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE archivo ADD CONSTRAINT FK_3529B482446C2E6 FOREIGN KEY (subido_por_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE archivo DROP CONSTRAINT FK_3529B482C51CDF3F');
        $this->addSql('ALTER TABLE archivo DROP CONSTRAINT FK_3529B482446C2E6');
        $this->addSql('DROP TABLE archivo');
    }
}
