<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260514184549 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, duration_seconds INT NOT NULL, status VARCHAR(20) NOT NULL, activity_type TEXT DEFAULT NULL, user_id INT NOT NULL, sala_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8849CBDEA76ED395 ON user_session (user_id)');
        $this->addSql('CREATE INDEX IDX_8849CBDEC51CDF3F ON user_session (sala_id)');
        $this->addSql('CREATE TABLE user_streak (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, current_streak INT NOT NULL, longest_streak INT NOT NULL, last_activity_date DATE NOT NULL, streak_start_date DATE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7CD80014A76ED395 ON user_streak (user_id)');
        $this->addSql('ALTER TABLE user_session ADD CONSTRAINT FK_8849CBDEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_session ADD CONSTRAINT FK_8849CBDEC51CDF3F FOREIGN KEY (sala_id) REFERENCES sala (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_streak ADD CONSTRAINT FK_7CD80014A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_session DROP CONSTRAINT FK_8849CBDEA76ED395');
        $this->addSql('ALTER TABLE user_session DROP CONSTRAINT FK_8849CBDEC51CDF3F');
        $this->addSql('ALTER TABLE user_streak DROP CONSTRAINT FK_7CD80014A76ED395');
        $this->addSql('DROP TABLE user_session');
        $this->addSql('DROP TABLE user_streak');
    }
}
