<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260409162941 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE mensaje (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenido TEXT NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, autor_id INT NOT NULL, sala_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9B631D0114D45BBE ON mensaje (autor_id)');
        $this->addSql('CREATE INDEX IDX_9B631D01C51CDF3F ON mensaje (sala_id)');
        $this->addSql('ALTER TABLE mensaje ADD CONSTRAINT FK_9B631D0114D45BBE FOREIGN KEY (autor_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mensaje ADD CONSTRAINT FK_9B631D01C51CDF3F FOREIGN KEY (sala_id) REFERENCES sala (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE mensaje DROP CONSTRAINT FK_9B631D0114D45BBE');
        $this->addSql('ALTER TABLE mensaje DROP CONSTRAINT FK_9B631D01C51CDF3F');
        $this->addSql('DROP TABLE mensaje');
    }
}
