<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260502021326 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE archivo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre_original VARCHAR(255) NOT NULL, nombre_servidor VARCHAR(255) NOT NULL, tipo VARCHAR(50) NOT NULL, sala_id INT NOT NULL, subido_por_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3529B482C51CDF3F ON archivo (sala_id)');
        $this->addSql('CREATE INDEX IDX_3529B482446C2E6 ON archivo (subido_por_id)');
        $this->addSql('CREATE TABLE mensaje (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenido TEXT DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, archivo_url VARCHAR(255) DEFAULT NULL, archivo_nombre VARCHAR(255) DEFAULT NULL, autor_id INT NOT NULL, sala_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9B631D0114D45BBE ON mensaje (autor_id)');
        $this->addSql('CREATE INDEX IDX_9B631D01C51CDF3F ON mensaje (sala_id)');
        $this->addSql('CREATE TABLE sala (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, categoria VARCHAR(100) NOT NULL, creador_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E226041C62F40C3D ON sala (creador_id)');
        $this->addSql('CREATE TABLE sala_user (sala_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (sala_id, user_id))');
        $this->addSql('CREATE INDEX IDX_AA4CE0BAC51CDF3F ON sala_user (sala_id)');
        $this->addSql('CREATE INDEX IDX_AA4CE0BAA76ED395 ON sala_user (user_id)');
        $this->addSql('CREATE TABLE tarea (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, foto_perfil VARCHAR(255) DEFAULT NULL, biografia TEXT DEFAULT NULL, ciudad VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE archivo ADD CONSTRAINT FK_3529B482C51CDF3F FOREIGN KEY (sala_id) REFERENCES sala (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE archivo ADD CONSTRAINT FK_3529B482446C2E6 FOREIGN KEY (subido_por_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mensaje ADD CONSTRAINT FK_9B631D0114D45BBE FOREIGN KEY (autor_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mensaje ADD CONSTRAINT FK_9B631D01C51CDF3F FOREIGN KEY (sala_id) REFERENCES sala (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sala ADD CONSTRAINT FK_E226041C62F40C3D FOREIGN KEY (creador_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sala_user ADD CONSTRAINT FK_AA4CE0BAC51CDF3F FOREIGN KEY (sala_id) REFERENCES sala (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sala_user ADD CONSTRAINT FK_AA4CE0BAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE archivo DROP CONSTRAINT FK_3529B482C51CDF3F');
        $this->addSql('ALTER TABLE archivo DROP CONSTRAINT FK_3529B482446C2E6');
        $this->addSql('ALTER TABLE mensaje DROP CONSTRAINT FK_9B631D0114D45BBE');
        $this->addSql('ALTER TABLE mensaje DROP CONSTRAINT FK_9B631D01C51CDF3F');
        $this->addSql('ALTER TABLE sala DROP CONSTRAINT FK_E226041C62F40C3D');
        $this->addSql('ALTER TABLE sala_user DROP CONSTRAINT FK_AA4CE0BAC51CDF3F');
        $this->addSql('ALTER TABLE sala_user DROP CONSTRAINT FK_AA4CE0BAA76ED395');
        $this->addSql('DROP TABLE archivo');
        $this->addSql('DROP TABLE mensaje');
        $this->addSql('DROP TABLE sala');
        $this->addSql('DROP TABLE sala_user');
        $this->addSql('DROP TABLE tarea');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
