<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260409154251 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE sala (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, categoria VARCHAR(100) NOT NULL, creador_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E226041C62F40C3D ON sala (creador_id)');
        $this->addSql('ALTER TABLE sala ADD CONSTRAINT FK_E226041C62F40C3D FOREIGN KEY (creador_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE sala DROP CONSTRAINT FK_E226041C62F40C3D');
        $this->addSql('DROP TABLE sala');
    }
}
